/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-0': 'var(--surface-0)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-subtle': 'var(--text-subtle)',
        'accent': 'var(--accent)',
        'accent-2': 'var(--accent-2)',
        'accent-3': 'var(--accent-3)',
        'accent-glow': 'var(--accent-glow)',
        'accent-soft': 'var(--accent-soft)',
        'accent-border': 'var(--accent-border)',
        'success': 'var(--success)',
        'success-soft': 'var(--success-soft)',
        'flag-amber': 'var(--amber)',
        'amber-soft': 'var(--amber-soft)',
        'border-theme': 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'glass-fill': 'var(--glass-fill)',
        'glass-border': 'var(--glass-border)',
        'evidence-bg': 'var(--evidence-bg)',
        'evidence-border': 'var(--evidence-border)',
        'evidence-text': 'var(--evidence-text)',
        'evidence-muted': 'var(--evidence-muted)',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Fira Code', 'Consolas', 'monospace'],
      },
      fontSize: {
        'xs': ['12px', { lineHeight: '16px' }],
        'sm': ['14px', { lineHeight: '20px' }],
        'base': ['16px', { lineHeight: '24px' }],
        'lg': ['18px', { lineHeight: '28px' }],
        'xl': ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '36px' }],
        '4xl': ['36px', { lineHeight: '40px' }],
        '5xl': ['48px', { lineHeight: '52px' }],
        '6xl': ['60px', { lineHeight: '64px' }],
        // Legacy scale names for backward compat
        'scale-13': ['13px', { lineHeight: '18px' }],
        'scale-15': ['15px', { lineHeight: '22px' }],
        'scale-17': ['17px', { lineHeight: '26px' }],
        'scale-22': ['22px', { lineHeight: '28px' }],
        'scale-28': ['28px', { lineHeight: '34px' }],
        'scale-36': ['36px', { lineHeight: '42px' }],
      },
      boxShadow: {
        'glow': '0 0 20px var(--accent-glow), 0 0 60px rgba(99,102,241,0.08)',
        'glow-sm': '0 0 8px var(--accent-glow)',
        'glow-lg': '0 0 40px var(--accent-glow), 0 0 80px rgba(99,102,241,0.12)',
        'glow-border': '0 0 0 1px var(--accent-border), 0 0 20px var(--accent-glow)',
        'card': '0 1px 3px rgba(0,0,0,0.3), 0 8px 24px rgba(0,0,0,0.2)',
        'elevated': '0 4px 16px rgba(0,0,0,0.4), 0 0 0 1px var(--border)',
      },
      borderRadius: {
        'xl': '12px',
        '2xl': '16px',
        '3xl': '24px',
      },
      backgroundImage: {
        'gradient-accent': 'linear-gradient(135deg, var(--gradient-start), var(--gradient-end))',
        'gradient-radial': 'radial-gradient(ellipse at center, var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        'float': 'float 4s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'pulse-ring': 'pulse-ring 2s ease-in-out infinite',
        'spin-slow': 'spin-slow 20s linear infinite',
        'aurora-1': 'aurora-1 12s ease-in-out infinite',
        'aurora-2': 'aurora-2 16s ease-in-out infinite',
        'aurora-3': 'aurora-3 10s ease-in-out infinite',
        'reveal-up': 'reveal-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'citation-glow': 'citation-glow 650ms ease-out forwards',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        'pulse-ring': {
          '0%': { boxShadow: '0 0 0 0 var(--accent-glow)' },
          '70%': { boxShadow: '0 0 0 8px rgba(99,102,241,0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(99,102,241,0)' },
        },
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'aurora-1': {
          '0%, 100%': { transform: 'translate(0%,0%) scale(1)', opacity: '0.5' },
          '33%': { transform: 'translate(3%,-4%) scale(1.05)', opacity: '0.7' },
          '66%': { transform: 'translate(-2%,2%) scale(0.95)', opacity: '0.5' },
        },
        'aurora-2': {
          '0%, 100%': { transform: 'translate(0%,0%) scale(1)', opacity: '0.4' },
          '33%': { transform: 'translate(-4%,3%) scale(1.08)', opacity: '0.6' },
          '66%': { transform: 'translate(3%,-2%) scale(0.92)', opacity: '0.4' },
        },
        'aurora-3': {
          '0%, 100%': { transform: 'translate(0%,0%) scale(1.2)', opacity: '0.3' },
          '50%': { transform: 'translate(2%,-3%) scale(1)', opacity: '0.5' },
        },
        'reveal-up': {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'citation-glow': {
          '0%': { boxShadow: '0 0 0 0 rgba(99,102,241,0)', background: 'transparent' },
          '35%': { boxShadow: '0 0 12px 3px var(--accent-glow)', background: 'var(--accent-soft)' },
          '100%': { boxShadow: '0 0 0 0 rgba(99,102,241,0)', background: 'transparent' },
        },
      },
      transitionDuration: {
        '200': '200ms',
        '300': '300ms',
        '400': '400ms',
      },
    },
  },
  plugins: [],
}
