/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-0':      'var(--surface-0)',
        'surface-1':      'var(--surface-1)',
        'surface-2':      'var(--surface-2)',
        'surface-3':      'var(--surface-3)',
        'surface-hover':  'var(--surface-hover)',
        'text-primary':   'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted':     'var(--text-muted)',
        'text-subtle':    'var(--text-subtle)',
        'accent':         'var(--accent)',
        'accent-dim':     'var(--accent-dim)',
        'accent-soft':    'var(--accent-soft)',
        'accent-border':  'var(--accent-border)',
        'border':         'var(--border)',
        'border-theme':   'var(--border)',
        'border-strong':  'var(--border-strong)',
        'success':        'var(--success)',
        'success-soft':   'var(--success-soft)',
        'danger':         'var(--danger)',
        'danger-soft':    'var(--danger-soft)',
        'warn':           'var(--warn)',
        'flag-amber':     'var(--warn)',
        'warn-soft':      'var(--warn-soft)',
        'evidence-bg':    'var(--evidence-bg)',
        'evidence-border':'var(--evidence-border)',
        'evidence-text':  'var(--evidence-text)',
        'evidence-muted': 'var(--evidence-muted)',
      },
      spacing: {
        '4.5': '1.125rem',
        '5.5': '1.375rem',
        '13': '3.25rem',
        '14': '3.5rem',
        '18': '4.5rem',
      },
      borderWidth: {
        '3': '3px',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Consolas', 'Menlo', 'monospace'],
      },
      fontSize: {
        'xs':   ['11px', { lineHeight: '16px' }],
        'sm':   ['13px', { lineHeight: '20px' }],
        'base': ['15px', { lineHeight: '24px' }],
        'lg':   ['17px', { lineHeight: '26px' }],
        'xl':   ['20px', { lineHeight: '28px' }],
        '2xl':  ['24px', { lineHeight: '30px' }],
        '3xl':  ['30px', { lineHeight: '36px' }],
        '4xl':  ['38px', { lineHeight: '44px' }],
        '5xl':  ['48px', { lineHeight: '54px' }],
        '6xl':  ['60px', { lineHeight: '64px' }],
        // Legacy compatibility
        'scale-13': ['13px', { lineHeight: '18px' }],
        'scale-15': ['15px', { lineHeight: '22px' }],
        'scale-17': ['17px', { lineHeight: '26px' }],
        'scale-22': ['22px', { lineHeight: '28px' }],
        'scale-28': ['28px', { lineHeight: '34px' }],
        'scale-36': ['36px', { lineHeight: '42px' }],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        DEFAULT: '8px',
        'md': '10px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '20px',
        '3xl': '28px',
        'full': '9999px',
      },
      boxShadow: {
        'xs': '0 1px 2px rgba(0,0,0,0.08)',
        'sm': '0 2px 6px rgba(0,0,0,0.12)',
        'card': '0 4px 20px -2px rgba(0,0,0,0.18)',
        'card-hover': '0 12px 36px -4px rgba(0,0,0,0.30)',
        'glass': '0 8px 32px 0 rgba(0, 0, 0, 0.28)',
        'glass-hover': '0 16px 48px -4px rgba(0, 0, 0, 0.40)',
        'elevated': '0 10px 30px -4px rgba(0,0,0,0.35)',
        'popover': '0 16px 40px -6px rgba(0,0,0,0.45)',
        'btn': '0 2px 10px -1px rgba(217, 119, 6, 0.35)',
        'btn-hover': '0 8px 24px -2px rgba(217, 119, 6, 0.45)',
        'inner-glass': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.08)',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'bounce-sm': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '250': '250ms',
        '300': '300ms',
      },
    },
  },
  plugins: [],
}
