/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-0':      'var(--surface-0)',
        'surface-1':      'var(--surface-1)',
        'surface-2':      'var(--surface-2)',
        'surface-3':      'var(--surface-3)',
        'surface-hover':  'var(--surface-hover)',
        'text-primary':   'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted':     'var(--text-muted)',
        'text-subtle':    'var(--text-subtle)',
        'accent':         'var(--accent)',
        'accent-dim':     'var(--accent-dim)',
        'accent-soft':    'var(--accent-soft)',
        'accent-border':  'var(--accent-border)',
        'border-theme':   'var(--border)',
        'border-strong':  'var(--border-strong)',
        'success':        'var(--success)',
        'success-soft':   'var(--success-soft)',
        'danger':         'var(--danger)',
        'danger-soft':    'var(--danger-soft)',
        'flag-amber':     'var(--warn)',
        'warn-soft':      'var(--warn-soft)',
        'evidence-bg':    'var(--evidence-bg)',
        'evidence-border':'var(--evidence-border)',
        'evidence-text':  'var(--evidence-text)',
        'evidence-muted': 'var(--evidence-muted)',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Consolas', 'Menlo', 'monospace'],
      },
      fontSize: {
        'xs':   ['11px', { lineHeight: '16px' }],
        'sm':   ['13px', { lineHeight: '20px' }],
        'base': ['15px', { lineHeight: '24px' }],
        'lg':   ['17px', { lineHeight: '26px' }],
        'xl':   ['20px', { lineHeight: '28px' }],
        '2xl':  ['24px', { lineHeight: '30px' }],
        '3xl':  ['30px', { lineHeight: '36px' }],
        '4xl':  ['38px', { lineHeight: '44px' }],
        '5xl':  ['48px', { lineHeight: '54px' }],
        '6xl':  ['60px', { lineHeight: '64px' }],
        // Legacy compatibility
        'scale-13': ['13px', { lineHeight: '18px' }],
        'scale-15': ['15px', { lineHeight: '22px' }],
        'scale-17': ['17px', { lineHeight: '26px' }],
        'scale-22': ['22px', { lineHeight: '28px' }],
        'scale-28': ['28px', { lineHeight: '34px' }],
        'scale-36': ['36px', { lineHeight: '42px' }],
      },
      borderRadius: {
        'sm': '3px',
        DEFAULT: '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '10px',
        '2xl': '14px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.25)',
        'elevated': '0 4px 12px rgba(0,0,0,0.35)',
        'popover': '0 8px 24px rgba(0,0,0,0.4)',
      },
      transitionDuration: {
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
      },
    },
  },
  plugins: [],
}
